In [13]:

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

In [14]:
warnings.filterwarnings('ignore')
sns.set(style="whitegrid")

In [18]:
df = pd.read_csv("/kaggle/input/heart-data/heart_data.csv")

In [19]:
print("First 5 rows:\n", df.head())

First 5 rows:
    Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  MaxHR  \
0   40   M           ATA        140          289          0     Normal    172
1   49   F           NAP        160          180          0     Normal    156
2   37   M           ATA        130          283          0         ST     98
3   48   F           ASY        138          214          0     Normal    108
4   54   M           NAP        150          195          0     Normal    122

  ExerciseAngina  Oldpeak ST_Slope  HeartDisease     AgeGroup  \
0              N      0.0       Up             0  Middle-aged
1              N      1.0     Flat             1  Middle-aged
2              N      0.0       Up             0        Young
3              Y      1.5     Flat             1  Middle-aged
4              N      0.0       Up             0  Middle-aged

  CholesterolStatus  RiskScore
0              High       9.47
1               Low       6.38
2              High       9.23
3   Borderline High       8.38
4               Low       6.93

In [21]:
print("\nData Info:")
print(df.info())

Data Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Age                918 non-null    int64
 1   Sex                918 non-null    object
 2   ChestPainType      918 non-null    object
 3   RestingBP          918 non-null    int64
 4   Cholesterol        918 non-null    int64
 5   FastingBS          918 non-null    int64
 6   RestingECG         918 non-null    object
 7   MaxHR              918 non-null    int64
 8   ExerciseAngina     918 non-null    object
 9   Oldpeak            918 non-null    float64
 10  ST_Slope           918 non-null    object
 11  HeartDisease       918 non-null    int64
 12  AgeGroup           918 non-null    object
 13  CholesterolStatus  918 non-null    object
 14  RiskScore          918 non-null    float64
dtypes: float64(2), int64(6), object(7)
memory usage: 107.7+ KB
None

In [22]:
print("\nSummary Statistics:\n", df.describe())

Summary Statistics:
               Age   RestingBP  Cholesterol   FastingBS       MaxHR  \
count  918.000000  918.000000   918.000000  918.000000  918.000000
mean    53.510893  132.396514   198.799564    0.233115  136.809368
std      9.432617   18.514154   109.384145    0.423046   25.460334
min     28.000000    0.000000     0.000000    0.000000   60.000000
25%     47.000000  120.000000   173.250000    0.000000  120.000000
50%     54.000000  130.000000   223.000000    0.000000  138.000000
75%     60.000000  140.000000   267.000000    0.000000  156.000000
max     77.000000  200.000000   603.000000    1.000000  202.000000

          Oldpeak  HeartDisease   RiskScore
count  918.000000    918.000000  918.000000
mean     0.887364      0.553377    7.547277
std      1.066570      0.497414    3.325547
min     -2.600000      0.000000    0.640000
25%      0.000000      0.000000    6.467500
50%      0.600000      1.000000    8.210000
75%      1.500000      1.000000    9.667500
max      6.200000      1.000000   20.170000

In [23]:
print("\nHeart Disease Distribution:\n", df['HeartDisease'].value_counts())

Heart Disease Distribution:
 HeartDisease
1    508
0    410
Name: count, dtype: int64